from random import randint
from os import system as sys
from art import logo

# declaring global variable 
EASY_LVL_TURNS = 10
HARD_LVL_TURNS = 5

def check_answer(chosen_num, comp_num):
    """Function compares number picked by player and number generated by computer.\nIf numbers are even function returns 0 and tell player their won,
else it returns 1 and tells player if their guess is too high or too low"""

    # checking if number chosen by player is equal, higher or lower than random number chosen by computer.
    # based on condition met giving feedback and returning specified value
    if chosen_num == comp_num:
        print(f"\nYou WIN! The number computer was thinking about is {comp_num}.")
        return 0

    elif chosen_num < comp_num:
        print("Too low.")
        return 1
    
    else:
        print("Too high.")
        return 1

def set_difficulty():
    """Function returns number of guessing attempts player will have based on chosen difficulty level."""

    # asking player to choose difficulty level
    diff_lvl = input("Choose a difficulty level. Type \"easy\" or \"hard\": ")

    # based on player choice of difficulty level returning fixed value
    if diff_lvl == "easy":
        return EASY_LVL_TURNS
    else:
        return HARD_LVL_TURNS

def the_number_guessing_game(help: bool = False):
    
    # clearing terminal
    sys("cls")
    print(logo)
    print("Welcome to the Number Guessing Game!\nI am thinking about number between 1 and 100.")
    rand_num = randint(1, 100)

    # based on function input value random chosen number can be shown to player
    if help is True:
        print(f"Psst... the number is {rand_num}.")
    
    # player guess attempts setting
    guess_num = set_difficulty()

    # variable responsible for main lopp lasting
    player_guessed = False

    # main loop in which player asked is for their guess, their answer is checked and based on it player gets feedback
    while player_guessed is not True and guess_num > 0:
        print(f"You have {guess_num} attempts remaining to guess number.")
        chosen_num = int(input("Make a guess:\n\n"))

        # checking for guess result, function itselfs gives player feedback if their guess was correct, too high or too low
        # based on function output variables responsible for loop execution are updated
        guess_result = check_answer(chosen_num, rand_num)
        if guess_result == 0:
            player_guessed = True
        else:
            guess_num -= 1
            if guess_num > 0:
                print("Guess again.")

    # condition is only met if player didn't guess the number and has no guess attempts left - player lost game
    if player_guessed is not True:
        print(f"\nYou lose. The number computer was thinking about is {rand_num}.")

if __name__ == "__main__":
    the_number_guessing_game()
