from random import randint
from os import system as sys
from art import logo

EASY_LVL_TURNS = 10
HARD_LVL_TURNS = 5

def check_answer(p_num, g_num):
    """Function compares number picked by player and number generated by computer.\nIf numbers are even function returns 0 and tell player their won,
else it returns 1 and tells player if their guess is too high or too low"""

    if p_num == g_num:
        print(f"\nYou WIN! The number computer was thinking about is {g_num}.")
        return 0

    elif chosen_num < rand_num:
        print("Too low.")
        return 1
    
    else:
        print("Too high.")
        return 1

def set_difficulty():
    """Function returns number of guessing attempts player will have based on chosen difficulty level."""
    diff_lvl = input("Chosoe a difficulty level. Type \"easy\" or \"hard\": ")

    if diff_lvl == "easy":
        return EASY_LVL_TURNS
    else:
        return HARD_LVL_TURNS

if __name__ == "__main__":
    sys("cls")
    print(logo)
    print("Welcome to the Number Guessing Game!\nI am thinking about number between 1 and 100.")
    rand_num = randint(1, 100)
    print(f"Psst... the number is {rand_num}.")
    player_guessed = False
    guess_num = set_difficulty()


    while player_guessed is not True and guess_num > 0:
        print(f"You have {guess_num} attempts remaining to guess number.")
        chosen_num = int(input("Make a guess:\n\n"))

        guess_result = check_answer(chosen_num, rand_num)
        if guess_result == 0:
            player_guessed = True
        else:
            guess_num -= 1
            if guess_num > 0:
                print("Guess again.")

    if player_guessed is not True:
        print(f"\nYou lose. The number computer was thinking about is {rand_num}.")
